image: kaiwinter/docker-java8-maven

stages:
    - build
    - test
    - deploy

stage-1:
    stage: build
    script:
        - mvn clean install

stage-2:
    stage: test
    script:
        - find . -name spring-eureka-server-0.0.1-SNAPSHOT.jar